//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualNumberManager
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericFault", Namespace="http://www.valitor.is/VirtualNumbers/1/2016")]
    public partial class GenericFault : object
    {
        
        private System.Exception ExceptionField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Exception
        {
            get
            {
                return this.ExceptionField;
            }
            set
            {
                this.ExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardData", Namespace="http://schemas.datacontract.org/2004/07/Valitor.Acquiring.VirtualNumbers.Contract" +
        "s.Data")]
    public partial class CardData : object
    {
        
        private string MaskedCardNumberField;
        
        private string ValidToDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaskedCardNumber
        {
            get
            {
                return this.MaskedCardNumberField;
            }
            set
            {
                this.MaskedCardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidToDate
        {
            get
            {
                return this.ValidToDateField;
            }
            set
            {
                this.ValidToDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.valitor.is/VirtualNumbers/1/2016", ConfigurationName="VirtualNumberManager.IVirtualNumberManager")]
    public interface IVirtualNumberManager
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.valitor.is/VirtualNumbers/1/2016/IVirtualNumberManager/GenerateNewVirt" +
            "ualNumber", ReplyAction="http://www.valitor.is/VirtualNumbers/1/2016/IVirtualNumberManager/GenerateNewVirt" +
            "ualNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VirtualNumberManager.GenericFault), Action="http://www.valitor.is/VirtualNumbers/1/2016/IVirtualNumberManager/GenerateNewVirt" +
            "ualNumberGenericFaultFault", Name="GenericFaultFault")]
        System.Threading.Tasks.Task<VirtualNumberManager.GenerateNewVirtualNumberResponse> GenerateNewVirtualNumberAsync(VirtualNumberManager.GenerateNewVirtualNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.valitor.is/VirtualNumbers/1/2016/IVirtualNumberManager/UpdateValidToDa" +
            "te", ReplyAction="http://www.valitor.is/VirtualNumbers/1/2016/IVirtualNumberManager/UpdateValidToDa" +
            "teResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VirtualNumberManager.GenericFault), Action="http://www.valitor.is/VirtualNumbers/1/2016/IVirtualNumberManager/UpdateValidToDa" +
            "teGenericFaultFault", Name="GenericFaultFault")]
        System.Threading.Tasks.Task<VirtualNumberManager.UpdateValidToDateResponse> UpdateValidToDateAsync(VirtualNumberManager.UpdateValidToDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.valitor.is/VirtualNumbers/1/2016/IVirtualNumberManager/GetCardData", ReplyAction="http://www.valitor.is/VirtualNumbers/1/2016/IVirtualNumberManager/GetCardDataResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VirtualNumberManager.GenericFault), Action="http://www.valitor.is/VirtualNumbers/1/2016/IVirtualNumberManager/GetCardDataGene" +
            "ricFaultFault", Name="GenericFaultFault")]
        System.Threading.Tasks.Task<VirtualNumberManager.GetCardDataResponse> GetCardDataAsync(VirtualNumberManager.GetCardDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.valitor.is/VirtualNumbers/1/2016/IVirtualNumberManager/GetCardNumber", ReplyAction="http://www.valitor.is/VirtualNumbers/1/2016/IVirtualNumberManager/GetCardNumberRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(VirtualNumberManager.GenericFault), Action="http://www.valitor.is/VirtualNumbers/1/2016/IVirtualNumberManager/GetCardNumberGe" +
            "nericFaultFault", Name="GenericFaultFault")]
        System.Threading.Tasks.Task<VirtualNumberManager.GetCardNumberResponse> GetCardNumberAsync(VirtualNumberManager.GetCardNumberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateNewVirtualNumber", WrapperNamespace="http://www.valitor.is/VirtualNumbers/1/2016", IsWrapped=true)]
    public partial class GenerateNewVirtualNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.valitor.is/VirtualNumbers/1/2016", Order=0)]
        public string cardNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.valitor.is/VirtualNumbers/1/2016", Order=1)]
        public string cvv;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.valitor.is/VirtualNumbers/1/2016", Order=2)]
        public string validToDate;
        
        public GenerateNewVirtualNumberRequest()
        {
        }
        
        public GenerateNewVirtualNumberRequest(string cardNumber, string cvv, string validToDate)
        {
            this.cardNumber = cardNumber;
            this.cvv = cvv;
            this.validToDate = validToDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateNewVirtualNumberResponse", WrapperNamespace="http://www.valitor.is/VirtualNumbers/1/2016", IsWrapped=true)]
    public partial class GenerateNewVirtualNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.valitor.is/VirtualNumbers/1/2016", Order=0)]
        public System.Guid GenerateNewVirtualNumberResult;
        
        public GenerateNewVirtualNumberResponse()
        {
        }
        
        public GenerateNewVirtualNumberResponse(System.Guid GenerateNewVirtualNumberResult)
        {
            this.GenerateNewVirtualNumberResult = GenerateNewVirtualNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateValidToDate", WrapperNamespace="http://www.valitor.is/VirtualNumbers/1/2016", IsWrapped=true)]
    public partial class UpdateValidToDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.valitor.is/VirtualNumbers/1/2016", Order=0)]
        public System.Guid virtualNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.valitor.is/VirtualNumbers/1/2016", Order=1)]
        public string validToDate;
        
        public UpdateValidToDateRequest()
        {
        }
        
        public UpdateValidToDateRequest(System.Guid virtualNumber, string validToDate)
        {
            this.virtualNumber = virtualNumber;
            this.validToDate = validToDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateValidToDateResponse", WrapperNamespace="http://www.valitor.is/VirtualNumbers/1/2016", IsWrapped=true)]
    public partial class UpdateValidToDateResponse
    {
        
        public UpdateValidToDateResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardData", WrapperNamespace="http://www.valitor.is/VirtualNumbers/1/2016", IsWrapped=true)]
    public partial class GetCardDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.valitor.is/VirtualNumbers/1/2016", Order=0)]
        public System.Guid virtualNumber;
        
        public GetCardDataRequest()
        {
        }
        
        public GetCardDataRequest(System.Guid virtualNumber)
        {
            this.virtualNumber = virtualNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardDataResponse", WrapperNamespace="http://www.valitor.is/VirtualNumbers/1/2016", IsWrapped=true)]
    public partial class GetCardDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.valitor.is/VirtualNumbers/1/2016", Order=0)]
        public VirtualNumberManager.CardData GetCardDataResult;
        
        public GetCardDataResponse()
        {
        }
        
        public GetCardDataResponse(VirtualNumberManager.CardData GetCardDataResult)
        {
            this.GetCardDataResult = GetCardDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardNumber", WrapperNamespace="http://www.valitor.is/VirtualNumbers/1/2016", IsWrapped=true)]
    public partial class GetCardNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.valitor.is/VirtualNumbers/1/2016", Order=0)]
        public System.Guid virtualNumber;
        
        public GetCardNumberRequest()
        {
        }
        
        public GetCardNumberRequest(System.Guid virtualNumber)
        {
            this.virtualNumber = virtualNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardNumberResponse", WrapperNamespace="http://www.valitor.is/VirtualNumbers/1/2016", IsWrapped=true)]
    public partial class GetCardNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.valitor.is/VirtualNumbers/1/2016", Order=0)]
        public string GetCardNumberResult;
        
        public GetCardNumberResponse()
        {
        }
        
        public GetCardNumberResponse(string GetCardNumberResult)
        {
            this.GetCardNumberResult = GetCardNumberResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IVirtualNumberManagerChannel : VirtualNumberManager.IVirtualNumberManager, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class VirtualNumberManagerClient : System.ServiceModel.ClientBase<VirtualNumberManager.IVirtualNumberManager>, VirtualNumberManager.IVirtualNumberManager
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VirtualNumberManagerClient() : 
                base(VirtualNumberManagerClient.GetDefaultBinding(), VirtualNumberManagerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IVirtualNumberManager.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VirtualNumberManagerClient(EndpointConfiguration endpointConfiguration) : 
                base(VirtualNumberManagerClient.GetBindingForEndpoint(endpointConfiguration), VirtualNumberManagerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VirtualNumberManagerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VirtualNumberManagerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VirtualNumberManagerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VirtualNumberManagerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VirtualNumberManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<VirtualNumberManager.GenerateNewVirtualNumberResponse> GenerateNewVirtualNumberAsync(VirtualNumberManager.GenerateNewVirtualNumberRequest request)
        {
            return base.Channel.GenerateNewVirtualNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<VirtualNumberManager.UpdateValidToDateResponse> UpdateValidToDateAsync(VirtualNumberManager.UpdateValidToDateRequest request)
        {
            return base.Channel.UpdateValidToDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<VirtualNumberManager.GetCardDataResponse> GetCardDataAsync(VirtualNumberManager.GetCardDataRequest request)
        {
            return base.Channel.GetCardDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<VirtualNumberManager.GetCardNumberResponse> GetCardNumberAsync(VirtualNumberManager.GetCardNumberRequest request)
        {
            return base.Channel.GetCardNumberAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IVirtualNumberManager))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                httpsBindingElement.AuthenticationScheme = System.Net.AuthenticationSchemes.Negotiate;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IVirtualNumberManager))
            {
                return new System.ServiceModel.EndpointAddress("https://s1-dbcacq-t0.visa.is/VirtualNumber/VirtualNumberManager.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VirtualNumberManagerClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IVirtualNumberManager);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VirtualNumberManagerClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IVirtualNumberManager);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IVirtualNumberManager,
        }
    }
}
